kat_kem.rsp: kat
	./run

kat: Makefile nist/kat_kem.c nist/rng.c nist/rng.h randombytes.h dec.c enc.c hide.c int32_sort.c keypair.c randomweightw.c rq_fromseed.c rq_mult.c rq_round3.c rq_rounded.c small.c    
	./build
