kat_kem.rsp: kat
	./run

kat: Makefile nist/kat_kem.c nist/rng.c nist/rng.h randombytes.h dec.c enc.c int32_sort.c keypair.c r3_mult.c r3_recip.c random32.c randomsmall.c randomweightw.c rq.c rq_mult.c rq_recip3.c rq_round3.c rq_rounded.c small.c swap.c    
	./build
